Repository tensorchord/envd-docs, pull requests merged in 2022-11, with the labels that each got.

#179 chore: update cuda & cudnn version, update dev guide
  docs-zh/blog/envd.md
  docs-zh/community/development.md
  docs-zh/envs/multitarget.md
  docs-zh/faq/why.md
  docs-zh/guide/build-envd.md
  docs-zh/tips/multitarget.md
  docs/blog/ml-env.md
  docs/community/development.md
  docs/faq/why.md
  docs/guide/build-envd.md
Labels: approved

#181 fix: Updated roadmap
  docs-zh/community/roadmap.md
  docs/community/roadmap.md
Labels: approved

#182 fix: Fix script in SD
  docs-zh/blog/stable-diffusion-cpu.md
Labels: lgtm, approved

#186 fix: link to train.ipynb
  docs/envs/multitarget.md
Labels: lgtm, approved

#189 feat: Add dev guide for envd-server
  docs-zh/blog/hacktoberfest.md
  docs-zh/guide/getting-started.md
  docs/.vitepress/config/sidebar/main.ts
  docs/blog/hacktoberfest.md
  docs/community/contributing.md
  docs/developers/assets/envd-arch.svg
  docs/developers/development.md
  docs/developers/kubernetes.md
  docs/guide/getting-started.md
Labels: lgtm

#198 chore: Add community info page
  docs-zh/.vitepress/config/sidebar/main.ts
  docs-zh/.vitepress/theme/custom.css
  docs-zh/community/community.md
  docs-zh/community/contributing.md
  docs-zh/developer/assets/envd-arch.svg
  docs-zh/developer/development.md
  docs-zh/developer/kubernetes.md
  docs/.vitepress/config/sidebar/main.ts
  docs/.vitepress/theme/custom.css
  docs/community/community.md
Labels: lgtm
