Repository tensorchord/envd-docs, pull requests merged in 2022-09, with the labels that each got.

#133 chore: Update docs for envd-sshd
  docs/community/development.md
  docs/zh/community/development.md
Labels: lgtm, approved

#140 fix: remove `zh` prefix
  README.md
Labels: lgtm

#143 chore: pnpm workspace
  docs-zh/pnpm-lock.yaml
  docs/package.json
  docs/pnpm-lock.yaml
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: lgtm, approved

#144 docs:chinese version
  docs-zh/envs/monitoring.md
Labels: lgtm, approved

#146 fix: Fix chinese website CI
  docs-zh/netlify.toml
Labels: lgtm, approved

#147 fix(envd-blog-post): Fix team section
  docs-zh/blog/envd.md
Labels: lgtm, approved

#149 update readme
  README.md
Labels: lgtm, approved

#151 doc: add comic to post
  docs/blog/ml-env.md
Labels: lgtm, approved

#152 update comic 2
  docs/blog/ml-env.md
Labels: lgtm, approved

#153 fix: cuda version
  docs-zh/blog/envd.md
  docs-zh/envs/multitarget.md
  docs-zh/faq/why.md
  docs-zh/guide/build-envd.md
  docs-zh/tips/multitarget.md
  docs/blog/ml-env.md
  docs/faq/why.md
  docs/guide/build-envd.md
Labels: lgtm, approved

#158 chore: Add a new post about hacktoberfest
  docs/.vitepress/config.ts
  docs/.vitepress/config/sidebar/blog.ts
  docs/blog/hacktoberfest.md
  docs/blog/welcome.md
Labels: approved

#160 fix: hacktoberfest font display
  docs/blog/hacktoberfest.md
Labels: lgtm, approved

#161 chore: fix cuda & cudnn version in the examples
  docs-zh/blog/envd.md
  docs-zh/envs/multitarget.md
  docs-zh/faq/why.md
  docs-zh/guide/build-envd.md
  docs-zh/tips/multitarget.md
  docs/blog/ml-env.md
  docs/faq/why.md
  docs/guide/build-envd.md
Labels: approved

#155 doc: Chinese docs update
  Makefile
  docs-zh/faq/comparison.md
  docs-zh/guide/build-envd.md
  docs-zh/guide/concepts.md
  docs-zh/guide/getting-started.md
  docs-zh/guide/ide.md
  docs-zh/teams/cache.md
  docs-zh/teams/ci.md
  docs-zh/teams/context.md
  docs-zh/teams/overview.md
  docs-zh/tips/multitarget.md
  docs/guide/getting-started.md
  hack/api/render.py
  package.json
  pnpm-lock.yaml
Labels: lgtm, approved
